<?php 
	_e("General Settings", "bannerrotator"); 
	_e("Google Font Settings", "bannerrotator"); 
	_e("Buttons", "bannerrotator"); 
	_e("Thumbnails", "bannerrotator"); 
	_e("Timer", "bannerrotator"); 
	_e("Appearance", "bannerrotator"); 
	_e("Position", "bannerrotator"); 
	_e("Troubleshooting", "bannerrotator"); 
	_e("Current Slide", "bannerrotator"); 
	_e("Change it if you want to start from a different slide then 1", "bannerrotator"); 
	_e("Delay", "bannerrotator"); 
	_e("The global time delay for image rotation", "bannerrotator"); 
	_e("Auto Play", "bannerrotator"); 
	_e("Initially start the slider", "bannerrotator"); 
	_e("Randomize", "bannerrotator"); 
	_e("Random slide order", "bannerrotator"); 
	_e("Lazy Load","bannerrotator"); 
	_e("The lazy load means that the images will be loaded by demand, it speeds the loading of the slider.","bannerrotator"); 
	_e("Touch Enabled", "bannerrotator"); 
	_e("Enable swipe function on touch devices", "bannerrotator"); 
	_e("Scroll Mouse Wheel", "bannerrotator"); 
	_e("Enable/disable mousewheel scroll", "bannerrotator"); 
	_e("Multi Language (WPML)", "bannerrotator"); 
	_e("Use the slide as mutli language - show multi language controls across the slider. This available only when wpml plugin exists", "bannerrotator");
	_e("Hide Caption Resolution", "bannerrotator"); 
	_e("Hide caption under the defined screen resolution", "bannerrotator"); 
	_e("Pause On Hover", "bannerrotator");
	_e("Pause slider timer on mouse hover", "bannerrotator"); 
	_e("Play Once", "bannerrotator");
	_e("Stop slider after all slides play once", "bannerrotator"); 
	_e("Select Slide On Hover", "bannerrotator");
	_e("Switch current slide on button hover", "bannerrotator"); 
	_e("Load Google Font", "bannerrotator"); 
	_e("Enable/disable Google font", "bannerrotator"); 
	_e("Google Font", "bannerrotator"); 
	_e("The google font family to load", "bannerrotator");	
	_e("Show Buttons", "bannerrotator"); 
	_e("Show the navigation buttons", "bannerrotator"); 
	_e("Show Number", "bannerrotator"); 
	_e("Show number label inside buttons", "bannerrotator"); 
	_e("Show Play/Pause Button", "bannerrotator"); 
	_e("Show play/pause button", "bannerrotator"); 
	_e("Show Directional Arrows", "bannerrotator"); 
	_e("Show previous/next arrow buttons in the navigation", "bannerrotator"); 
	_e("Show Center Arrows", "bannerrotator"); 
	_e("Show side directional arrow buttons on the center", "bannerrotator"); 
	_e("Show Buttons On Hover", "bannerrotator"); 
	_e("Show navigation buttons on hover", "bannerrotator"); 
	_e("Button Align", "bannerrotator"); 
	_e("Horizontal/vertical button alignment", "bannerrotator"); 
	_e("Button Width", "bannerrotator"); 
	_e("The width of the buttons", "bannerrotator"); 
	_e("Button Height", "bannerrotator"); 
	_e("The height of the buttons", "bannerrotator"); 
	_e("Button Border Radius", "bannerrotator"); 
	_e("Rounded corner radius of buttons", "bannerrotator"); 
	_e("Button Margin", "bannerrotator"); 
	_e("The margin size between thumbnails/buttons", "bannerrotator"); 
	_e("Horizontal Offset", "bannerrotator"); 
	_e("Nagivation bar can be moved this pixel count left(e.g. -10) or right", "bannerrotator"); 
	_e("Vertical Offset", "bannerrotator"); 
	_e("Nagivation bar can be moved this pixel count up (e. g. 20) or down", "bannerrotator"); 
	_e("Show Thumbnails", "bannerrotator"); 
	_e("Show thumbnails instead of buttons", "bannerrotator"); 
	_e("Thumb Width", "bannerrotator"); 
	_e("The basic Width of one Thumbnail (only if thumbnails are visible)", "bannerrotator"); 
	_e("Thumb Height", "bannerrotator"); 
	_e("The basic Height of one Thumbnail (only if thumbnails are visible)", "bannerrotator"); 
	_e("Show Timer", "bannerrotator"); 
	_e("Show the timer", "bannerrotator"); 
	_e("Timer Type", "bannerrotator"); 
	_e("The timer bar type", "bannerrotator"); 
	_e("Clock Timer Arc Size", "bannerrotator"); 
	_e("Clock timer arc size", "bannerrotator"); 
	_e("Timer Align", "bannerrotator"); 
	_e("Set the timer indicator line position to bottom or top", "bannerrotator"); 
	_e("Shadow Type", "bannerrotator"); 
	_e("The Shadow display underneath the banner. The shadow apply to fixed and responsive modes only, the full width slider don't have a shadow.", "bannerrotator"); 
	_e("Show Tolltip", "bannerrotator"); 
	_e("Show image/text tooltip", "bannerrotator"); 
	_e("Tooltip Type", "bannerrotator"); 
	_e("The tooltip type", "bannerrotator"); 
	_e("Background Color", "bannerrotator"); 
	_e("Slider wrapper div background color, for transparent slider, leave empty.", "bannerrotator"); 
	_e("Padding (border)", "bannerrotator"); 
	_e("The wrapper div padding, if it has value, then together with background color it it will make border around the slider.", "bannerrotator"); 
	_e("Show Background Image", "bannerrotator"); 
	_e("Put background image to the main slider wrapper", "bannerrotator"); 
	_e("Background Image Url", "bannerrotator"); 
	_e("The background image that will be on the slider wrapper. Will be shown at slider preloading.", "bannerrotator"); 
	_e("Position On The Page", "bannerrotator"); 
	_e("The position of the slider on the page, (float:left, float:right, margin:0px auto;)", "bannerrotator"); 
	_e("Margin Top", "bannerrotator"); 
	_e("The top margin of the slider wrapper div", "bannerrotator"); 
	_e("Margin Bottom", "bannerrotator"); 
	_e("The bottom margin of the slider wrapper div", "bannerrotator"); 
	_e("Margin Left", "bannerrotator"); 
	_e("The left margin of the slider wrapper div", "bannerrotator"); 
	_e("Margin Right", "bannerrotator"); 
	_e("The right margin of the slider wrapper div", "bannerrotator"); 
	_e("JQuery No Conflict Mode", "bannerrotator"); 
	_e("Turns on / off jquery noconflict mode. You can play with this option when you have some javascript conflicts.", "bannerrotator"); 
	_e("Put JS Includes To Body", "bannerrotator"); 
	_e("Putting the js to body (in addition to head) is good for fixing some javascript conflicts of type: TypeError: jQuery('#banner_rotator_1_1').show().bannerRotator is not a function", "bannerrotator"); 
	_e("Output Filters Protection", "bannerrotator"); 
	_e("Activate a protection against wordpress output filters that adds html blocks to the shortcode output like P and BR", "bannerrotator");
?>